services:

# 'zabbix-server', the backend
  z72pg:
    image: zabbix/zabbix-server-pgsql:7.2.15-alpine
    container_name: z72pg
    environment:
      ZBX_DEBUGLEVEL: '3'
      DB_SERVER_HOST: '10.88.74.18'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'z72'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_USER: 'zabbix'
      TZ: 'Europe/Riga'
      ZBX_ALLOWUNSUPPORTED18ERSIONS: '1'
      ZBX_CACHESIZE: '256M'
      ZBX_STARTAGENTPOLLERS: '1'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
#      ZBX_WEBDRIVERURL: '172.22.141.24:4444'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '1'

    ports:
      - "17251:10051"
    networks:
      podnet:
        ipv4_address: 10.88.2.172
    tty: true
    restart: unless-stopped

# passive Zabbix proxy
  z72passive:
    image: zabbix/zabbix-proxy-sqlite3:7.2.15-alpine
    container_name: z72passive
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'z72passive'
      ZBX_PROXYMODE: '1'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.172'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "37251:10051"
    networks:
      podnet:
        ipv4_address: 10.88.3.172
    tty: true
    restart: unless-stopped

# active Zabbix proxy
  z72active:
    image: zabbix/zabbix-proxy-sqlite3:7.2.15-alpine
    container_name: z72active
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'z72active'
      ZBX_PROXYMODE: '0'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.172'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "47251:10051"
    networks:
      podnet:
        ipv4_address: 10.88.4.172
    tty: true
    restart: unless-stopped

# Zabbix GUI with NGINX
  z72web:
    image: zabbix/zabbix-web-nginx-pgsql:7.2.15-alpine
    container_name: z72web
    environment:
      DB_SERVER_HOST: '10.88.74.18'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'z72'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: '10.88.2.172'
      ZBX_SERVER_PORT: '10051'
      PHP_TZ: 'Europe/Riga'

    volumes:
      - '${HOME}/z72modules:/usr/share/zabbix/modules'
      - '${HOME}/Dropbox/docker/volume/nginx:/etc/ssl/nginx'

    ports:
      - "8072:8080"
      - "44372:8443"
    networks:
      podnet:
        ipv4_address: 10.88.1.172
    tty: true
    restart: unless-stopped

networks:
  podnet:
    name: DockerInternalNet
    external: true

