services:
  z70.my.httpd:
    image: zabbix/zabbix-web-apache-mysql:7.0.29-alpine
    container_name: z70.my.httpd
    environment:
      DEBUG_MODE: 'TRUE'
      DB_SERVER_HOST: '10.88.8.0'
      DB_SERVER_PORT: '3306'
      MYSQL_DATABASE: 'z70'
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'password'
      ZBX_SERVER_HOST: '10.88.2.170'
      ZBX_SERVER_PORT: '10051'
      PHP_TZ: 'Europe/Riga'
      ZBX_VAULT: 'HashiCorp'
      ZBX_VAULTURL: 'https://thisIsURL.com:8200/v1/secret/data/zabbix'
      ZBX_VAULTDBPATH: 'zabbix/server_database'
      VAULT_TOKEN: 'abc123'
      

    ports:
      - "18070:8080"
    networks:
      podnet:
        ipv4_address: 10.88.11.170
    tty: true
    restart: unless-stopped

networks:
  podnet:
    name: DockerInternalNet
    external: true

