services:
  z70my:
    image: zabbix/zabbix-server-mysql:7.0.29-alpine
    container_name: z70my
    environment:
      DB_SERVER_HOST: '10.88.8.0'
      DB_SERVER_PORT: '3306'
      MYSQL_DB: 'zabbix'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'zabbix'
      TZ: 'Europe/Riga'
      ZBX_DEBUGLEVEL: '3'
      ZBX_ALLOWUNSUPPORTED17ERSIONS: '1'
      ZBX_CACHESIZE: '256M'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '1'

#    ports:
 #     - "17051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.12.170
    tty: true
    restart: unless-stopped


networks:
  podnet:
    name: DockerInternalNet
    external: true

