services:

# 'zabbix-server', the backend
  z70pg:
    image: zabbix/zabbix-server-pgsql:7.0.27-alpine
    container_name: z70pg
    environment:
      ZBX_DEBUGLEVEL: '3'
      DB_SERVER_HOST: '10.88.74.17'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'z70'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_USER: 'zabbix'
      TZ: 'Europe/Riga'
      ZBX_ALLOWUNSUPPORTED17ERSIONS: '1'
      ZBX_CACHESIZE: '256M'
      ZBX_STARTAGENTPOLLERS: '1'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '1'

    ports:
      - "17051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.2.170
    tty: true
    restart: unless-stopped

# passive Zabbix proxy
  z70passive:
    image: zabbix/zabbix-proxy-sqlite3:7.0.27-alpine
    container_name: z70passive
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'z70passive'
      ZBX_PROXYMODE: '1'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.170'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "37051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.3.170
    tty: true
    restart: unless-stopped

# active Zabbix proxy
  z70active:
    image: zabbix/zabbix-proxy-sqlite3:7.0.27-alpine
    container_name: z70active
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'z70active'
      ZBX_PROXYMODE: '0'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.170'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "47051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.4.170
    tty: true
    restart: unless-stopped

# Zabbix GUI with NGINX
  z70web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.27-alpine
    container_name: z70web
    environment:
      DB_SERVER_HOST: '10.88.74.17'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'z70'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: '10.88.2.170'
      ZBX_SERVER_PORT: '10051'
      PHP_TZ: 'Europe/Riga'

    volumes:
      - '${HOME}/z70modules:/usr/share/zabbix/modules'
      - '${HOME}/Dropbox/docker/volume/nginx:/etc/ssl/nginx'

    ports:
      - "8070:8080"
      - "44370:8443"
    networks:
      podnet:
        ipv4_address: 10.88.1.170
    tty: true
    restart: unless-stopped

networks:
  podnet:
    name: DockerInternalNet
    external: true

