services:

# 'zabbix-server', the backend
  zXypg:
    image: zabbix/zabbix-server-pgsql:X.Y.Z-alpine
    container_name: zXypg
    environment:
      ZBX_DEBUGLEVEL: '3'
      DB_SERVER_HOST: '10.88.74.DBV'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'zXy'
      POSTGRES_PASSWORD: 'zabbix'
      POSTGRES_USER: 'zabbix'
      TZ: 'Europe/Riga'
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: '1'
      ZBX_CACHESIZE: '256M'
      ZBX_STARTAGENTPOLLERS: '1'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '1'

    ports:
      - "1Xy51:10051"
    networks:
      podnet:
        ipv4_address: 10.88.2.1Xy
    tty: true
    restart: unless-stopped

# passive Zabbix proxy
  zXypassive:
    image: zabbix/zabbix-proxy-sqlite3:X.Y.Z-alpine
    container_name: zXypassive
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'zXypassive'
      ZBX_PROXYMODE: '1'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.1Xy'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "3Xy51:10051"
    networks:
      podnet:
        ipv4_address: 10.88.3.1Xy
    tty: true
    restart: unless-stopped

# active Zabbix proxy
  zXyactive:
    image: zabbix/zabbix-proxy-sqlite3:X.Y.Z-alpine
    container_name: zXyactive
    environment:
      ZBX_DEBUGLEVEL: '3'
      ZBX_HOSTNAME: 'zXyactive'
      ZBX_PROXYMODE: '0'
      TZ: 'Europe/Riga'
      ZBX_CACHESIZE: '256M'
      ZBX_SERVER_HOST: '10.88.2.1Xy'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '1'
      ZBX_STARTHTTPPOLLERS: '1'
      ZBX_STARTPINGERS: '1'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '1'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "4Xy51:10051"
    networks:
      podnet:
        ipv4_address: 10.88.4.1Xy
    tty: true
    restart: unless-stopped

# Zabbix GUI with NGINX
  zXyweb:
    image: zabbix/zabbix-web-nginx-pgsql:X.Y.Z-alpine
    container_name: zXyweb
    environment:
      DB_SERVER_HOST: '10.88.74.DBV'
      DB_SERVER_PORT: '5432'
      POSTGRES_DB: 'zXy'
      POSTGRES_USER: 'zabbix'
      POSTGRES_PASSWORD: 'zabbix'
      ZBX_SERVER_HOST: '10.88.2.1Xy'
      ZBX_SERVER_PORT: '10051'
      PHP_TZ: 'Europe/Riga'

    volumes:
      - '${HOME}/zXymodules:/usr/share/zabbix/modules'
      - '${HOME}/Dropbox/docker/volume/nginx:/etc/ssl/nginx'

    ports:
      - "80Xy:8080"
      - "443Xy:8443"
    networks:
      podnet:
        ipv4_address: 10.88.1.1Xy
    tty: true
    restart: unless-stopped

networks:
  podnet:
    name: DockerInternalNet
    external: true

